### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by hakemi7** [Vincenzo160/project-landscape#4]
**Describe the bug**
When i open the file it instantly crash

**To Reproduce**
1. Open lanscapeWin.py

**Expected behavior**
Open the script

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.3

**Additional context**

**Comment by Vincenzo160** [comment]
Hi, can you try to open a terminal and type `python3` and drag the file, then copy and paste the output and send it

**Comment by hakemi7** [comment]
Ok this is the outuput
[Version: 1.3 [BETA]
Project landscape
/!\ ATTENTION /!\
If your client don't save the log in the minecraft folder this program won't function
Traceback (most recent call last):
  File "C:\Users\Vincenzo\Downloads\landscapeWin.py", line 30, in <module>
    matching_lines = [line for line in open(path).readlines() if pattern in line] # please edit /Users/vincenzodeluca/Library/...
FileNotFoundError: [Errno 2] No such file or directory: '%appdata%/.minecraft/logs/latest.log']

**Comment by Vincenzo160** [comment]
Ok, what client you use?

**Comment by hakemi7** [comment]
i don't use a client

**Comment by Vincenzo160** [comment]
You intend the Minecraft vanilla client?

**Comment by hakemi7** [comment]
yep

**Comment by Vincenzo160** [comment]
Ok, try to open landscape.py whit notepad,

1. press win + r
2. type `%appdata%/.minecraft/logs`
3. right click on latest.log
4. open propeties
5. copy the path
6. paste it on the 12 line of the code after the ' replacing `%appdata%/.minecraft/logs/latest.log`

**Comment by hakemi7** [comment]
it contune to crash

**Comment by Vincenzo160** [comment]
can you try to open a terminal and type python3 and drag the file, then copy and paste the output and send it

**Comment by hakemi7** [comment]
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by Vincenzo160** [comment]
If you have used `\` in the path try replacing it whit `/`

**Comment by hakemi7** [comment]
NameError: name 'm' is not defined

**Comment by Vincenzo160** [comment]
This can be a problem whit the beta, try to download the stable version [here](https://github.com/Vincenzo160/project-landscape/releases/tag/1.2) and redo the procedure of copying and pasting the path changing the `\` whit `/`

Please if you want report the problem that you experienced on the beta [here](Crash if there is not any GEXP)

**Comment by hakemi7** [comment]
When i type g and press enter it crash

AttributeError: 'list' object has no attribute 'group'

**Comment by Vincenzo160** [comment]
You can send me a screenshot of the menu?

**Comment by hakemi7** [comment]
https://bit.ly/2U2gnSJ

**Comment by Vincenzo160** [comment]
you can just send the Imgur link? please

**Comment by hakemi7** [comment]
https://i.imgur.com/HDES5su.png

**Comment by Vincenzo160** [comment]
It crashes cause you don't have any GEXP on your last session of Minecraft, try farming some GEXP and retry

**Comment by hakemi7** [comment]
ok
